# Site settings
title: Michał Czerwiński
name: Michał Czerwiński

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/m-czerwinski
 - title: LinkedIn
   url: https://www.linkedin.com/in/micha%C5%82-czerwi%C5%84ski-9954281b4/

#Any buzzword skills you want to include
skills:
 - name: ERP Systems - SAP
   Level: Basic
 - name: Docker
   Level: Basic
 - name: Soft skills - team leading
   Level: Advanced
 - name: AWS EC2 and Cloud Services
   Level: Basic
 - name: Linux System Administration
   Level: Basic
 - name:  Windows Core Administration
   Level: Intermediate

#Area of Expertise
expertise:
  - name: Self sufficient
    description: Strong drive and ability to self-organize.
  - name: Great language skills
    description: Native level English; good understanding of Dutch and German
  - name: Team Player
    description: Working great with a group to solve problems and find solutions; helping to coordinate. 
  - name: Problem Solver
    description: Considers problems as a puzzle and enjoys finding a creative yet appropriate solutions.

#Work experience is required
roles:
 - title: Supply Chain Management Agent
   start: 08.2021
   end: 12.2021
   employer: Maersk Group
   description: Overseeing the supply chain for Maersk customers; ensuring proper document flow and its compliance
   place: Gdynia, Poland
 - title: HR Compliance Associate
   start: 02.2021
   end: 06.2021
   employer: Maersk Drilling
   description: Reviewing of compliance of personnel certifications with maritime standards and regulations
   place: Gdańsk, Poland
 - title: Senior Compliance Associate - Extended Producer Responsibility
   start: 01.2019
   end: 09.2020
   employer: Amazon
   description: Customs categorisation for electronic waste; deep diving and researching chemical composition specific customs rules
   place: Kraków, Poland
 - title: Senior Compliance Associate - Global Trade
   start: 12.2017
   end: 01.2019
   employer: Amazon
   description: In-depth customs review of products; Rulewriting for automatisation of aforementioned;  
   place: Gdańsk, Poland
 - title: UK Team Lead
   start: 10.2014
   end: 05.2017
   employer: Ray-Ban
   description: Coordinating UK Customer Care team; Ensuring quality of service
   place: Gdansk, Poland

#Education is required
education:
 - title: Logistician
   start: 2010
   end: 2013
   subject: Logistics and Sea Spedition
   school: Gdynia Maritime University

#Contact flair is optional
contact:
   phone: +48 666 112 691
   email: md.czerwinski@gmail.com 

intro: |
  <p>I am an engineer with 5 years’ experience working in technology. I have primarily worked on the Windows-related web stack, but have worked across a broad range of technologies thereon: Groovy, Linux, Docker and most recently Openshift and Kubernetes; as well as spending a reasonable amount of time building applications for the web, which has given me an exposure to a range of web-related skills (Graphic design, coding, services, workflows, AWS integrations).</p>

  <p>I enjoy working with interesting products, with understanding of business-related topics, management and emphasis on DevOps culture. Due to my work with consultancy agencies I have a strong understanding of processes, engineering principals and communication with clients and stakeholders.</p>

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
    <strong>Cloud platforms</strong>: I have primarily used AWS for running production apps on the cloud. I have experience setting up, configuring and running applications using a range of AWS offerings, including EC2, RDS, S3, Cogito, Lambda.<br/><br/>
    <strong>Web Development</strong>: Through building web applications, I have also worked with various client side technology, having used jQuery, Bootstrap, LESS, SASS.<br/><br/>
    <strong>Development Control</strong>: I have a good knowledge of application life-cycle management and have worked with SVN, Git, Maven, Gradle, Sonar, Jenkins, TeamCity, etc. I have experience with an array of testing tools and technologies.<br/><br/>
