# Site settings
title: Michał Czerwiński
name: Michał Czerwiński

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/m-czerwinski
 - title: LinkedIn
   url: https://www.linkedin.com/in/micha%C5%82-czerwi%C5%84ski-9954281b4/

#Any buzzword skills you want to include
skills:
 - name: ERP Systems - SAP
   percent: 25%
 - name: HTML & CSS
   percent: 25%
 - name: Agile Methodology
   percent: 50%
 - name: Docker
   percent: 50%
 - name: Soft skills and team-leading
   percent: 75%
 - name: SQL
   percent: 50%
 - name: Linux System Administration
   percent: 50%
 - name:  Windows Core Administration and Active Directory
   percent: 50%
  - name: Jira; Confluence; TeamViewer
   percent: 75%

#Area of Expertise
expertise:
  - name: Detail oriented
    description: Always focused on details; 
  - name: Self-sufficient
    description: Strong drive and ability to self-organize.
  - name: Great language skills
    description: Native level English; good understanding of Dutch and German
  - name: Team Player
    description: Working great with a group to solve problems and find solutions; helping to coordinate. 
  - name: Problem Solver
    description: Considers problems as a puzzle and enjoys finding creative yet appropriate solutions.

#Work experience is required
roles:

 - title: Tech Support - 2nd Line
   start: 12.2022
   end: Ongoing
   employer: Ocean Technologies Group
   
   place: "Assisting customers with everyday issues;Writing simple SQL queries; Configuring POP3; SMTP and FTP services; Troubleshooting"
   
 - title: DevOps Intern
   start: 03.2022
   end: 12.2022
   employer: Michal Suwara IT
   place: "Learning basics of DevOps by assisting the employer; Writing dockerfiles; Basics of Kubernetes"
   
 - title: Supply Chain Management Agent
   start: 08.2021
   end: 12.2021
   employer: Maersk Group
   place: "Overseeing the supply chain for Maersk customers; ensuring proper document flow and its compliance"
   
 - title: HR Compliance Associate
   start: 02.2021
   end: 06.2021
   employer: Maersk Drilling
   place: "Reviewing of compliance of personnel certifications with maritime standards and regulations"
   
 - title: Senior Compliance Associate - Extended Producer Responsibility
   start: 01.2019
   end: 09.2020
   employer: Amazon
   place: "Customs categorization for electronic waste; deep diving and researching chemical composition-specific customs rules"
   
 - title: Senior Compliance Associate - Global Trade
   start: 12.2017
   end: 01.2019
   employer: Amazon
   place: "In-depth customs review of products; Rule writing for automatization of aforementioned; Coordinating work with QA"  
   
 - title: UK Team Lead
   start: 10.2014
   end: 05.2017
   employer: Ray-Ban
   place: "Coordinating UK Customer Care team; Ensuring quality of service; Dealing with difficult and problematic cases"

#Education is required
education:
 - title: Logistician
   start: 2010
   end: 2013
   subject: Logistics and Sea Spedition
   school: Gdynia Maritime University
  
#Contact flair is optional
contact:
   phone: +48 666 112 691
   email: md.czerwinski@gmail.com 
   
   
intro: <p>
           Wyrażam zgodę na przetwarzanie moich danych osobowych dla potrzeb niezbędnych do realizacji procesu rekrutacji 
           zgodnie z Rozporządzeniem Parlamentu Europejskiego i Rady (UE) 2016/679 z dnia 27 kwietnia 2016 r. w sprawie ochrony osób fizycznych 
            w związku z przetwarzaniem danych osobowych i w sprawie swobodnego przepływu takich danych oraz uchylenia dyrektywy 95/46/WE (RODO).

I hereby consent to the processing of this CV and the personal data contained within, by anyone who receives this document for the sole purpose of considering my application for employment opportunities, in accordance with Article 6.1(a) of GDPR (EU) 2016/679.




 </p>
