# Site settings
title: Michał Czerwiński
name: Michał Czerwiński

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/m-czerwinski
 - title: LinkedIn
   url: https://www.linkedin.com/in/micha%C5%82-czerwi%C5%84ski-9954281b4/

#Any buzzword skills you want to include
skills:
 - name: ERP Systems - SAP
   Level: Basic
 - name: Docker
   Level: Basic
 - name: Soft skills - team leading
   Level: Advanced
 - name: AWS EC2 and Cloud Services
   Level: Basic
 - name: Linux System Administration
   Level: Basic
 - name:  Windows Core Administration
   Level: Intermediate

#Area of Expertise
expertise:
  - name: Detail oriented
    description: Always focused on details; 
  - name: Self sufficient
    description: Strong drive and ability to self-organize.
  - name: Great language skills
    description: Native level English; good understanding of Dutch and German
  - name: Team Player
    description: Working great with a group to solve problems and find solutions; helping to coordinate. 
  - name: Problem Solver
    description: Considers problems as a puzzle and enjoys finding a creative yet appropriate solutions.

#Work experience is required
roles:
 - title: Supply Chain Management Agent
   start: 08.2021
   end: 12.2021
   employer: Maersk Group
   description: Overseeing the supply chain for Maersk customers; ensuring proper document flow and its compliance
   place: Gdynia, Poland
 - title: HR Compliance Associate
   start: 02.2021
   end: 06.2021
   employer: Maersk Drilling
   description: Reviewing of compliance of personnel certifications with maritime standards and regulations
   place: Gdańsk, Poland
 - title: Senior Compliance Associate - Extended Producer Responsibility
   start: 01.2019
   end: 09.2020
   employer: Amazon
   description: Customs categorisation for electronic waste; deep diving and researching chemical composition specific customs rules
   place: Kraków, Poland
 - title: Senior Compliance Associate - Global Trade
   start: 12.2017
   end: 01.2019
   employer: Amazon
   description: In-depth customs review of products; Rulewriting for automatisation of aforementioned;  
   place: Gdańsk, Poland
 - title: UK Team Lead
   start: 10.2014
   end: 05.2017
   employer: Ray-Ban
   description: Coordinating UK Customer Care team; Ensuring quality of service
   place: Gdansk, Poland

#Education is required
education:
 - title: Logistician
   start: 2010
   end: 2013
   subject: Logistics and Sea Spedition
   school: Gdynia Maritime University

#Contact flair is optional
contact:
   phone: +48 666 112 691
   email: md.czerwinski@gmail.com 

